# Generated by Django 6.0.4 on 2026-05-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последней активности'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Серия дней'),
        ),
    ]
