# Generated by Django 6.0.4 on 2026-04-30 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('level', models.CharField(choices=[('A1', 'Начальный A1'), ('A2', 'Элементарный A2'), ('B1', 'Средний B1'), ('B2', 'Выше среднего B2'), ('C1', 'Продвинутый C1')], max_length=2, verbose_name='Уровень')),
                ('category', models.CharField(choices=[('general', 'Общий английский'), ('it', 'Английский в IT'), ('business', 'Бизнес английский'), ('travel', 'Английский для путешествий')], default='general', max_length=50, verbose_name='Категория')),
                ('is_public', models.BooleanField(default=True, verbose_name='Открытый курс')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Изображение курса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_comments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий к курсу',
                'verbose_name_plural': 'Комментарии к курсам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название урока')),
                ('content', models.TextField(verbose_name='Материал урока')),
                ('order', models.PositiveIntegerField(verbose_name='Порядковый номер')),
                ('points_reward', models.PositiveIntegerField(default=10, verbose_name='Баллы за прохождение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('choice', 'Выбор одного ответа'), ('text_input', 'Ввод ответа текстом'), ('translate', 'Перевод фразы'), ('fill_gap', 'Заполнение пропуска'), ('order_words', 'Сбор предложения из слов')], max_length=30, verbose_name='Тип упражнения')),
                ('question', models.TextField(verbose_name='Задание')),
                ('source_text', models.TextField(blank=True, verbose_name='Исходный текст')),
                ('option_1', models.CharField(blank=True, max_length=255, verbose_name='Вариант 1')),
                ('option_2', models.CharField(blank=True, max_length=255, verbose_name='Вариант 2')),
                ('option_3', models.CharField(blank=True, max_length=255, verbose_name='Вариант 3')),
                ('option_4', models.CharField(blank=True, max_length=255, verbose_name='Вариант 4')),
                ('correct_option', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Вариант 1'), (2, 'Вариант 2'), (3, 'Вариант 3'), (4, 'Вариант 4')], null=True, verbose_name='Правильный вариант')),
                ('correct_answer', models.CharField(blank=True, max_length=500, verbose_name='Правильный ответ')),
                ('words_for_ordering', models.TextField(blank=True, verbose_name='Слова для сборки предложения')),
                ('explanation', models.TextField(blank=True, verbose_name='Объяснение после ответа')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок упражнения')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='courses.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_access_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на доступ к курсу',
                'verbose_name_plural': 'Заявки на доступ к курсам',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
