# Generated by Django 6.0.4 on 2026-05-06 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lessonresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonresult',
            name='points_earned',
            field=models.PositiveIntegerField(default=0, verbose_name='Полученные баллы'),
        ),
        migrations.AlterField(
            model_name='lessonresult',
            name='best_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Лучший результат в процентах'),
        ),
        migrations.AlterField(
            model_name='lessonresult',
            name='completed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего прохождения'),
        ),
        migrations.AlterField(
            model_name='lessonresult',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='courses.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='lessonresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_results', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
