# Generated by Django 6.0.4 on 2026-06-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lessonresult_points_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата скрытия курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Курс скрыт'),
        ),
    ]
